fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.1
  hooks:
    # Run the linter.
    - id: ruff
      name: Ruff Linter
      args: [ check, --fix ]
    # Run the formatter.
    - id: ruff-format
      name: Ruff Formatter
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0  # Use the sha / tag you want to point at
  hooks:
    - id: mypy
      name: Type Checker
      args: ["--ignore-missing-imports"]
# pytest
