# User Specified
run_name: pdam
work_dir: pdam_results
sequence_path: data/protein_seqs_700.fasta
protein_shortlist: data/pdam_shortlist.txt
go_shortlist: data/pdam_shortlist_go.txt

build_cytoscape: true

####################

# General Parameters
seed: 6191998

# hmmscan Parameters
hmmscan:
  path: hmmscan
  threads: 16

# D-SCRIPT Parameters
n_pairs: 500000
manual_annot_wt: 100
dscript:
  model: human_v1.sav
  device: 0

# DSD Parameters
dsd:
  t: 0.0

# Clustering Parameters
# clustering:
#   init_k: 500
#   min_cluster_size: 3
#   cluster_divisor: 20
clustering:
  init_k: 3
  min_cluster_size: 1
  cluster_divisor: 2

# ReCIPE Parameters
recipe:
  lr: 0.1
  cthresh: 0.75
  max: 20
  metric: degree

# Cytoscape Parameters

# Langchain Parameters
langchain:
  do_llm: false
  model: gpt-4o
