# User Specified
run_name: pdam
work_dir: /mnt/home/ssledzieski/data/philharmonic/p_damicornis/results
sequence_path: /mnt/ceph/users/ssledzieski/philharmonic/p_damicornis/pdam_toy.fasta
use_cytoscape: false
use_langchain: false

############################################

# General Parameters
seed: 6191998

# hmmscan Parameters
hmmscan:
  path: hmmscan
  threads: 16

# D-SCRIPT Parameters
dscript:
  path: dscript
  n_pairs: -1
  model: human_v1.sav
  device: 0

# DSD Parameters
dsd:
  path: fastdsd
  t: 0.0
  confidence: true

# Clustering Parameters
clustering:
  init_k: 5
  min_cluster_size: 5
  cluster_divisor: 5

# ReCIPE Parameters
recipe:
  lr: 0.1
  cthresh: 0.75
  max_proteins: 20
  metric: degree

# Langchain Parameters
langchain:
  model: gpt-4o
