# User Specified
run_name: pdam
work_dir: pdam_results
sequence_path: data/protein_seqs_700.fasta
protein_shortlist: data/pdam_shortlist.txt
go_shortlist: data/pdam_shortlist_go.txt
use_cytoscape: false
use_langchain: false

############################################

# General Parameters
seed: 6191998

# hmmscan Parameters
hmmscan:
  path: hmmscan
  threads: 16

# D-SCRIPT Parameters
dscript:
  path: dscript
  n_pairs: 500000
  manual_annot_wt: 100
  model: human_v1.sav
  device: 0

# DSD Parameters
dsd:
  path: fastdsd
  t: 0.0
  confidence: true

# Clustering Parameters
clustering:
  init_k: 500
  min_cluster_size: 3
  cluster_divisor: 20

# ReCIPE Parameters
recipe:
  lr: 0.1
  cthresh: 0.75
  max_proteins: 20
  metric: degree

# Langchain Parameters
langchain:
  model: gpt-4o
