# User Specified
run_name: philharmonic
sequence_path: sample_sequences.fasta
go_filter_path: assets/go_filter.txt
work_dir: results
use_cytoscape: false
use_langchain: false

############################################

# General Parameters
seed: 6191998

# hmmscan Parameters
hmmscan:
  path: hmmscan
  threads: 32

# D-SCRIPT Parameters
dscript:
  path: dscript
  n_pairs: -1
  model: human_v1.sav
  device: 0

# DSD Parameters
dsd:
  path: fastdsd
  t: 0.5
  confidence: true

# Clustering Parameters
clustering:
  init_k: 500
  min_cluster_size: 3
  cluster_divisor: 20
  sparsity_thresh: 1e-5

# ReCIPE Parameters
recipe:
  lr: 0.1
  cthresh: 0.75
  max_proteins: 20
  metric: degree

# Langchain Parameters
langchain:
  model: gpt-4o
